name: Ambassadorship Application
description: KubeSphere Ambassadorship Program (KSAP) is a program where we bring together our members who carry out community activities for KubeSphere. 
labels: [ "area/ambassadorship-application" ]
title: "Application: 2023 Ambassadorship Program Application <your-GH-handle>"
assignees: halil-bugol
body:
- id: github
  type: input
  attributes:
    label: GitHub Username
    placeholder: e.g. @example_user
  validations:
    required: true
- id: name
  type: input
  attributes:
    label: Name
  validations:
    required: true
- id: surname
  type: input
  attributes:
    label: Surname
  validations:
    required: true
- id: basic-requirements
  type: checkboxes
  attributes:
    label: Basic Requirements
    options:
    - label:  Must be 18 years of age or older.
      required: true
    - label:  You need to have active knowledge of Cloud Native architectures.
      required: true
    - label:  To have technological or other knowledge that will contribute to the future of KubeSphere.
      required: true     
- id: requirements
  type: checkboxes
  attributes:
    label: Basic Requirements
    options:
    - label:  To have published a minimum of four pieces of content in the last year (e.g., blogs, social media posts, videos etc.)
      required: false
    - label:  Contribute to any of the KubeSphere repos a minimum of twenty times in the past year
      required: false
    - label:  Organized an event on behalf of KubeSphere or made a presentation on behalf of KubeSphere at an organized event at least once in the last year.
      required: false
    - label:  Be an active community supporter or Ambassador in a minimum of two CNCF Member or Projects.
      required: false
- id: sponsor_1
  type: input
  attributes:
    label: "Sponsor 1"
    description: GitHub handle of your sponsor
    placeholder: e.g. @sponsor-1
  validations:
    required: true
- id: sponsor_2
  type: input
  attributes:
    label: "Sponsor 2"
    description: GitHub handle of your sponsor
    placeholder: e.g. @sponsor-2
  validations:
    required: true
- id: contributions
  type: textarea
  attributes:
    label: List of contributions to the Kubernetes project
    placeholder: |
      - PRs reviewed / authored
      - Issues responded to
      - SIG projects I am involved with
  validations:
    required: true



